package org.homwork.pojo;

import java.util.HashSet;
import java.util.Set;

// Generated 2017-9-12 19:43:37 by Hibernate Tools 3.6.0.Final

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7680262318353382983L;
	private Integer classid;
	private String name;
	private Set<Student> students = new HashSet<>();
	
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Classes [classid=" + classid + ", name=" + name + "]";
	}

	/**
	 * @return the classid
	 */
	public Integer getClassid() {
		return classid;
	}

	/**
	 * @param classid the classid to set
	 */
	public void setClassid(Integer classid) {
		this.classid = classid;
	}

	/**
	 * @return the students
	 */
	public Set<Student> getStudents() {
		return students;
	}

	/**
	 * @param students the students to set
	 */
	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	public Classes() {
	}

	public Classes(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
